// Demo catalog data — generated for the storefront demo. Not real inventory.
const PRODUCTS = [
  {
    "id": 1,
    "name": "پارس‌تک یخچال و فریزر دو قلو نوفراست",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "پارس‌تک",
    "model": "FR-1000",
    "price": 43290000,
    "power": 318,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 2,
    "name": "کیان‌الکتریک یخچال و فریزر ساید بای ساید",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "کیان‌الکتریک",
    "model": "FR-1007",
    "price": 44300000,
    "power": 343,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 3,
    "name": "نوین‌هوم یخچال و فریزر بالا پایین",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "نوین‌هوم",
    "model": "FR-1014",
    "price": 45010000,
    "power": 124,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 4,
    "name": "زرین لوازم یخچال و فریزر تک درب",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "زرین لوازم",
    "model": "FR-1021",
    "price": 54350000,
    "power": 419,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 5,
    "name": "آریانا هوم یخچال و فریزر فریزر ایستاده",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "آریانا هوم",
    "model": "FR-1028",
    "price": 26100000,
    "power": 184,
    "material": null,
    "warranty": 24,
    "inStock": false,
    "rating": 3.9
  },
  {
    "id": 6,
    "name": "دلتا خانه یخچال و فریزر دو قلو نوفراست",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "دلتا خانه",
    "model": "FR-1035",
    "price": 21170000,
    "power": 136,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 7,
    "name": "سپهر الکتریک یخچال و فریزر ساید بای ساید",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "سپهر الکتریک",
    "model": "FR-1042",
    "price": 28430000,
    "power": 315,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.8
  },
  {
    "id": 8,
    "name": "بامو تک یخچال و فریزر بالا پایین",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "بامو تک",
    "model": "FR-1049",
    "price": 61180000,
    "power": 148,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4
  },
  {
    "id": 9,
    "name": "پارس‌تک یخچال و فریزر تک درب",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "پارس‌تک",
    "model": "FR-1056",
    "price": 29370000,
    "power": 236,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.3
  },
  {
    "id": 10,
    "name": "کیان‌الکتریک یخچال و فریزر فریزر ایستاده",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "کیان‌الکتریک",
    "model": "FR-1063",
    "price": 30580000,
    "power": 286,
    "material": null,
    "warranty": 12,
    "inStock": false,
    "rating": 4
  },
  {
    "id": 11,
    "name": "نوین‌هوم یخچال و فریزر دو قلو نوفراست",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "نوین‌هوم",
    "model": "FR-1070",
    "price": 38530000,
    "power": 319,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.5
  },
  {
    "id": 12,
    "name": "زرین لوازم یخچال و فریزر ساید بای ساید",
    "category": "fridge",
    "categoryLabel": "یخچال و فریزر",
    "icon": "fridge",
    "brand": "زرین لوازم",
    "model": "FR-1077",
    "price": 35590000,
    "power": 120,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.6
  },
  {
    "id": 13,
    "name": "آریانا هوم ماشین لباسشویی درب از جلو ۸ کیلویی",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "آریانا هوم",
    "model": "WA-1084",
    "price": 17570000,
    "power": 2219,
    "material": null,
    "warranty": 36,
    "inStock": false,
    "rating": 3.7
  },
  {
    "id": 14,
    "name": "دلتا خانه ماشین لباسشویی درب از جلو ۹ کیلویی",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "دلتا خانه",
    "model": "WA-1091",
    "price": 13430000,
    "power": 1894,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.8
  },
  {
    "id": 15,
    "name": "سپهر الکتریک ماشین لباسشویی درب از بالا",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "سپهر الکتریک",
    "model": "WA-1098",
    "price": 28960000,
    "power": 2178,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.7
  },
  {
    "id": 16,
    "name": "بامو تک ماشین لباسشویی خشک‌کن دار",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "بامو تک",
    "model": "WA-1105",
    "price": 14450000,
    "power": 1871,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 17,
    "name": "پارس‌تک ماشین لباسشویی کم مصرف A+++",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "پارس‌تک",
    "model": "WA-1112",
    "price": 22070000,
    "power": 1958,
    "material": null,
    "warranty": 18,
    "inStock": false,
    "rating": 4
  },
  {
    "id": 18,
    "name": "کیان‌الکتریک ماشین لباسشویی درب از جلو ۸ کیلویی",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "کیان‌الکتریک",
    "model": "WA-1119",
    "price": 26390000,
    "power": 2165,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.9
  },
  {
    "id": 19,
    "name": "نوین‌هوم ماشین لباسشویی درب از جلو ۹ کیلویی",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "نوین‌هوم",
    "model": "WA-1126",
    "price": 29320000,
    "power": 2171,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 20,
    "name": "زرین لوازم ماشین لباسشویی درب از بالا",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "زرین لوازم",
    "model": "WA-1133",
    "price": 12060000,
    "power": 2194,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 21,
    "name": "آریانا هوم ماشین لباسشویی خشک‌کن دار",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "آریانا هوم",
    "model": "WA-1140",
    "price": 16900000,
    "power": 2233,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.7
  },
  {
    "id": 22,
    "name": "دلتا خانه ماشین لباسشویی کم مصرف A+++",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "دلتا خانه",
    "model": "WA-1147",
    "price": 18180000,
    "power": 1849,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 23,
    "name": "سپهر الکتریک ماشین لباسشویی درب از جلو ۸ کیلویی",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "سپهر الکتریک",
    "model": "WA-1154",
    "price": 13240000,
    "power": 2227,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 24,
    "name": "بامو تک ماشین لباسشویی درب از جلو ۹ کیلویی",
    "category": "washer",
    "categoryLabel": "ماشین لباسشویی",
    "icon": "washer",
    "brand": "بامو تک",
    "model": "WA-1161",
    "price": 30890000,
    "power": 1902,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 25,
    "name": "پارس‌تک ماشین ظرفشویی ۱۲ نفره",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "پارس‌تک",
    "model": "DI-1168",
    "price": 19480000,
    "power": 1886,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 26,
    "name": "کیان‌الکتریک ماشین ظرفشویی ۱۴ نفره",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "کیان‌الکتریک",
    "model": "DI-1175",
    "price": 25360000,
    "power": 1605,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.4
  },
  {
    "id": 27,
    "name": "نوین‌هوم ماشین ظرفشویی رومیزی",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "نوین‌هوم",
    "model": "DI-1182",
    "price": 25520000,
    "power": 1773,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.7
  },
  {
    "id": 28,
    "name": "زرین لوازم ماشین ظرفشویی دیجیتال با نمایشگر",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "زرین لوازم",
    "model": "DI-1189",
    "price": 26180000,
    "power": 1765,
    "material": null,
    "warranty": 36,
    "inStock": false,
    "rating": 3.7
  },
  {
    "id": 29,
    "name": "آریانا هوم ماشین ظرفشویی بی‌صدا",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "آریانا هوم",
    "model": "DI-1196",
    "price": 27280000,
    "power": 1916,
    "material": null,
    "warranty": 12,
    "inStock": false,
    "rating": 3.4
  },
  {
    "id": 30,
    "name": "دلتا خانه ماشین ظرفشویی ۱۲ نفره",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "دلتا خانه",
    "model": "DI-1203",
    "price": 16400000,
    "power": 1862,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 31,
    "name": "سپهر الکتریک ماشین ظرفشویی ۱۴ نفره",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "سپهر الکتریک",
    "model": "DI-1210",
    "price": 27120000,
    "power": 1845,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 32,
    "name": "بامو تک ماشین ظرفشویی رومیزی",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "بامو تک",
    "model": "DI-1217",
    "price": 17900000,
    "power": 1809,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.5
  },
  {
    "id": 33,
    "name": "پارس‌تک ماشین ظرفشویی دیجیتال با نمایشگر",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "پارس‌تک",
    "model": "DI-1224",
    "price": 16280000,
    "power": 1739,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.6
  },
  {
    "id": 34,
    "name": "کیان‌الکتریک ماشین ظرفشویی بی‌صدا",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "کیان‌الکتریک",
    "model": "DI-1231",
    "price": 24950000,
    "power": 2016,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 35,
    "name": "نوین‌هوم ماشین ظرفشویی ۱۲ نفره",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "نوین‌هوم",
    "model": "DI-1238",
    "price": 30530000,
    "power": 1627,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 36,
    "name": "زرین لوازم ماشین ظرفشویی ۱۴ نفره",
    "category": "dishwasher",
    "categoryLabel": "ماشین ظرفشویی",
    "icon": "dishwasher",
    "brand": "زرین لوازم",
    "model": "DI-1245",
    "price": 26040000,
    "power": 1958,
    "material": null,
    "warranty": 12,
    "inStock": false,
    "rating": 3.6
  },
  {
    "id": 37,
    "name": "آریانا هوم اجاق گاز و هود ۵ شعله فردار",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "آریانا هوم",
    "model": "ST-1252",
    "price": 17380000,
    "power": 135,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 38,
    "name": "دلتا خانه اجاق گاز و هود شیشه‌ای رومیزی",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "دلتا خانه",
    "model": "ST-1259",
    "price": 15470000,
    "power": 130,
    "material": null,
    "warranty": 12,
    "inStock": false,
    "rating": 3.6
  },
  {
    "id": 39,
    "name": "سپهر الکتریک اجاق گاز و هود توکار",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "سپهر الکتریک",
    "model": "ST-1266",
    "price": 14850000,
    "power": 141,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.5
  },
  {
    "id": 40,
    "name": "بامو تک اجاق گاز و هود هود مخفی",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "بامو تک",
    "model": "ST-1273",
    "price": 13550000,
    "power": 137,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.3
  },
  {
    "id": 41,
    "name": "پارس‌تک اجاق گاز و هود هود شومینه‌ای",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "پارس‌تک",
    "model": "ST-1280",
    "price": 11030000,
    "power": 120,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.8
  },
  {
    "id": 42,
    "name": "کیان‌الکتریک اجاق گاز و هود ۵ شعله فردار",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "کیان‌الکتریک",
    "model": "ST-1287",
    "price": 21000000,
    "power": 125,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 43,
    "name": "نوین‌هوم اجاق گاز و هود شیشه‌ای رومیزی",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "نوین‌هوم",
    "model": "ST-1294",
    "price": 6980000,
    "power": 198,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.9
  },
  {
    "id": 44,
    "name": "زرین لوازم اجاق گاز و هود توکار",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "زرین لوازم",
    "model": "ST-1301",
    "price": 18910000,
    "power": 200,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 45,
    "name": "آریانا هوم اجاق گاز و هود هود مخفی",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "آریانا هوم",
    "model": "ST-1308",
    "price": 15100000,
    "power": 181,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.7
  },
  {
    "id": 46,
    "name": "دلتا خانه اجاق گاز و هود هود شومینه‌ای",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "دلتا خانه",
    "model": "ST-1315",
    "price": 22720000,
    "power": 164,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.5
  },
  {
    "id": 47,
    "name": "سپهر الکتریک اجاق گاز و هود ۵ شعله فردار",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "سپهر الکتریک",
    "model": "ST-1322",
    "price": 6750000,
    "power": 179,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 48,
    "name": "بامو تک اجاق گاز و هود شیشه‌ای رومیزی",
    "category": "stove",
    "categoryLabel": "اجاق گاز و هود",
    "icon": "stove",
    "brand": "بامو تک",
    "model": "ST-1329",
    "price": 10130000,
    "power": 219,
    "material": null,
    "warranty": 36,
    "inStock": false,
    "rating": 4.5
  },
  {
    "id": 49,
    "name": "پارس‌تک مایکروویو توام با گریل",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "پارس‌تک",
    "model": "MI-1336",
    "price": 7720000,
    "power": 1198,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.4
  },
  {
    "id": 50,
    "name": "کیان‌الکتریک مایکروویو دیجیتال",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "کیان‌الکتریک",
    "model": "MI-1343",
    "price": 7990000,
    "power": 1125,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 51,
    "name": "نوین‌هوم مایکروویو رومیزی ساده",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "نوین‌هوم",
    "model": "MI-1350",
    "price": 11860000,
    "power": 1247,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.2
  },
  {
    "id": 52,
    "name": "زرین لوازم مایکروویو توکار",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "زرین لوازم",
    "model": "MI-1357",
    "price": 11950000,
    "power": 803,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.8
  },
  {
    "id": 53,
    "name": "آریانا هوم مایکروویو با فر همرفتی",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "آریانا هوم",
    "model": "MI-1364",
    "price": 10950000,
    "power": 839,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.4
  },
  {
    "id": 54,
    "name": "دلتا خانه مایکروویو توام با گریل",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "دلتا خانه",
    "model": "MI-1371",
    "price": 10070000,
    "power": 1044,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.7
  },
  {
    "id": 55,
    "name": "سپهر الکتریک مایکروویو دیجیتال",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "سپهر الکتریک",
    "model": "MI-1378",
    "price": 10840000,
    "power": 1342,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 56,
    "name": "بامو تک مایکروویو رومیزی ساده",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "بامو تک",
    "model": "MI-1385",
    "price": 12960000,
    "power": 930,
    "material": null,
    "warranty": 18,
    "inStock": false,
    "rating": 4.6
  },
  {
    "id": 57,
    "name": "پارس‌تک مایکروویو توکار",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "پارس‌تک",
    "model": "MI-1392",
    "price": 9760000,
    "power": 1008,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 58,
    "name": "کیان‌الکتریک مایکروویو با فر همرفتی",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "کیان‌الکتریک",
    "model": "MI-1399",
    "price": 5960000,
    "power": 872,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 59,
    "name": "نوین‌هوم مایکروویو توام با گریل",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "نوین‌هوم",
    "model": "MI-1406",
    "price": 5720000,
    "power": 908,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 60,
    "name": "زرین لوازم مایکروویو دیجیتال",
    "category": "microwave",
    "categoryLabel": "مایکروویو",
    "icon": "microwave",
    "brand": "زرین لوازم",
    "model": "MI-1413",
    "price": 11680000,
    "power": 1145,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 61,
    "name": "آریانا هوم جاروبرقی رباتیک",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "آریانا هوم",
    "model": "VA-1420",
    "price": 3380000,
    "power": 850,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 62,
    "name": "دلتا خانه جاروبرقی بدون کیسه",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "دلتا خانه",
    "model": "VA-1427",
    "price": 8000000,
    "power": 1562,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 63,
    "name": "سپهر الکتریک جاروبرقی عمودی شارژی",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "سپهر الکتریک",
    "model": "VA-1434",
    "price": 14700000,
    "power": 853,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.3
  },
  {
    "id": 64,
    "name": "بامو تک جاروبرقی سطلی",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "بامو تک",
    "model": "VA-1441",
    "price": 5430000,
    "power": 525,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 65,
    "name": "پارس‌تک جاروبرقی دستی شارژی",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "پارس‌تک",
    "model": "VA-1448",
    "price": 7190000,
    "power": 542,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 66,
    "name": "کیان‌الکتریک جاروبرقی رباتیک",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "کیان‌الکتریک",
    "model": "VA-1455",
    "price": 4140000,
    "power": 930,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.7
  },
  {
    "id": 67,
    "name": "نوین‌هوم جاروبرقی بدون کیسه",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "نوین‌هوم",
    "model": "VA-1462",
    "price": 4940000,
    "power": 1362,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 68,
    "name": "زرین لوازم جاروبرقی عمودی شارژی",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "زرین لوازم",
    "model": "VA-1469",
    "price": 10280000,
    "power": 471,
    "material": null,
    "warranty": 18,
    "inStock": false,
    "rating": 4.9
  },
  {
    "id": 69,
    "name": "آریانا هوم جاروبرقی سطلی",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "آریانا هوم",
    "model": "VA-1476",
    "price": 9420000,
    "power": 1429,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.4
  },
  {
    "id": 70,
    "name": "دلتا خانه جاروبرقی دستی شارژی",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "دلتا خانه",
    "model": "VA-1483",
    "price": 11850000,
    "power": 1669,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4
  },
  {
    "id": 71,
    "name": "سپهر الکتریک جاروبرقی رباتیک",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "سپهر الکتریک",
    "model": "VA-1490",
    "price": 10250000,
    "power": 683,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.6
  },
  {
    "id": 72,
    "name": "بامو تک جاروبرقی بدون کیسه",
    "category": "vacuum",
    "categoryLabel": "جاروبرقی",
    "icon": "vacuum",
    "brand": "بامو تک",
    "model": "VA-1497",
    "price": 3480000,
    "power": 648,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 73,
    "name": "پارس‌تک کولر و پنکه آبی پرتابل",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "پارس‌تک",
    "model": "FA-1504",
    "price": 3600000,
    "power": 410,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 74,
    "name": "کیان‌الکتریک کولر و پنکه گازی اسپیلت",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "کیان‌الکتریک",
    "model": "FA-1511",
    "price": 8490000,
    "power": 815,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.3
  },
  {
    "id": 75,
    "name": "نوین‌هوم کولر و پنکه ایستاده",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "نوین‌هوم",
    "model": "FA-1518",
    "price": 13950000,
    "power": 454,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.2
  },
  {
    "id": 76,
    "name": "زرین لوازم کولر و پنکه سقفی",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "زرین لوازم",
    "model": "FA-1525",
    "price": 2700000,
    "power": 279,
    "material": null,
    "warranty": 18,
    "inStock": false,
    "rating": 4.5
  },
  {
    "id": 77,
    "name": "آریانا هوم کولر و پنکه تصفیه هوای همراه",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "آریانا هوم",
    "model": "FA-1532",
    "price": 14800000,
    "power": 484,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.3
  },
  {
    "id": 78,
    "name": "دلتا خانه کولر و پنکه آبی پرتابل",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "دلتا خانه",
    "model": "FA-1539",
    "price": 17820000,
    "power": 440,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.5
  },
  {
    "id": 79,
    "name": "سپهر الکتریک کولر و پنکه گازی اسپیلت",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "سپهر الکتریک",
    "model": "FA-1546",
    "price": 5380000,
    "power": 652,
    "material": null,
    "warranty": 24,
    "inStock": false,
    "rating": 4.2
  },
  {
    "id": 80,
    "name": "بامو تک کولر و پنکه ایستاده",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "بامو تک",
    "model": "FA-1553",
    "price": 4930000,
    "power": 76,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 81,
    "name": "پارس‌تک کولر و پنکه سقفی",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "پارس‌تک",
    "model": "FA-1560",
    "price": 20710000,
    "power": 844,
    "material": null,
    "warranty": 24,
    "inStock": false,
    "rating": 3.5
  },
  {
    "id": 82,
    "name": "کیان‌الکتریک کولر و پنکه تصفیه هوای همراه",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "کیان‌الکتریک",
    "model": "FA-1567",
    "price": 4020000,
    "power": 389,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 83,
    "name": "نوین‌هوم کولر و پنکه آبی پرتابل",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "نوین‌هوم",
    "model": "FA-1574",
    "price": 2170000,
    "power": 563,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 84,
    "name": "زرین لوازم کولر و پنکه گازی اسپیلت",
    "category": "fan",
    "categoryLabel": "کولر و پنکه",
    "icon": "fan",
    "brand": "زرین لوازم",
    "model": "FA-1581",
    "price": 10130000,
    "power": 381,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 85,
    "name": "آریانا هوم اتو و بخارشو بخار عمودی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "آریانا هوم",
    "model": "IR-1588",
    "price": 3700000,
    "power": 2390,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 86,
    "name": "دلتا خانه اتو و بخارشو شارژی بی‌سیم",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "دلتا خانه",
    "model": "IR-1595",
    "price": 3400000,
    "power": 2449,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 87,
    "name": "سپهر الکتریک اتو و بخارشو مسافرتی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "سپهر الکتریک",
    "model": "IR-1602",
    "price": 4830000,
    "power": 1657,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.8
  },
  {
    "id": 88,
    "name": "بامو تک اتو و بخارشو با مخزن آب بزرگ",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "بامو تک",
    "model": "IR-1609",
    "price": 940000,
    "power": 1480,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.5
  },
  {
    "id": 89,
    "name": "پارس‌تک اتو و بخارشو حرفه‌ای خیاطی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "پارس‌تک",
    "model": "IR-1616",
    "price": 6130000,
    "power": 2186,
    "material": null,
    "warranty": 18,
    "inStock": false,
    "rating": 3.4
  },
  {
    "id": 90,
    "name": "کیان‌الکتریک اتو و بخارشو بخار عمودی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "کیان‌الکتریک",
    "model": "IR-1623",
    "price": 3060000,
    "power": 2077,
    "material": null,
    "warranty": 36,
    "inStock": false,
    "rating": 4
  },
  {
    "id": 91,
    "name": "نوین‌هوم اتو و بخارشو شارژی بی‌سیم",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "نوین‌هوم",
    "model": "IR-1630",
    "price": 4230000,
    "power": 1277,
    "material": null,
    "warranty": 12,
    "inStock": false,
    "rating": 4.9
  },
  {
    "id": 92,
    "name": "زرین لوازم اتو و بخارشو مسافرتی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "زرین لوازم",
    "model": "IR-1637",
    "price": 3000000,
    "power": 2075,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 93,
    "name": "آریانا هوم اتو و بخارشو با مخزن آب بزرگ",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "آریانا هوم",
    "model": "IR-1644",
    "price": 4910000,
    "power": 1751,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 94,
    "name": "دلتا خانه اتو و بخارشو حرفه‌ای خیاطی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "دلتا خانه",
    "model": "IR-1651",
    "price": 4870000,
    "power": 1262,
    "material": null,
    "warranty": 36,
    "inStock": false,
    "rating": 4.7
  },
  {
    "id": 95,
    "name": "سپهر الکتریک اتو و بخارشو بخار عمودی",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "سپهر الکتریک",
    "model": "IR-1658",
    "price": 1650000,
    "power": 2525,
    "material": null,
    "warranty": 36,
    "inStock": false,
    "rating": 4.5
  },
  {
    "id": 96,
    "name": "بامو تک اتو و بخارشو شارژی بی‌سیم",
    "category": "iron",
    "categoryLabel": "اتو و بخارشو",
    "icon": "iron",
    "brand": "بامو تک",
    "model": "IR-1665",
    "price": 2930000,
    "power": 1707,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 97,
    "name": "پارس‌تک لوازم آشپزخانه برقی توستر نان",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "پارس‌تک",
    "model": "KI-1672",
    "price": 6550000,
    "power": 388,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.3
  },
  {
    "id": 98,
    "name": "کیان‌الکتریک لوازم آشپزخانه برقی چای‌ساز",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "کیان‌الکتریک",
    "model": "KI-1679",
    "price": 5900000,
    "power": 649,
    "material": null,
    "warranty": 24,
    "inStock": false,
    "rating": 4
  },
  {
    "id": 99,
    "name": "نوین‌هوم لوازم آشپزخانه برقی آبمیوه‌گیری",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "نوین‌هوم",
    "model": "KI-1686",
    "price": 1160000,
    "power": 1558,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 100,
    "name": "زرین لوازم لوازم آشپزخانه برقی همزن آشپزخانه",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "زرین لوازم",
    "model": "KI-1693",
    "price": 5890000,
    "power": 1087,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 101,
    "name": "آریانا هوم لوازم آشپزخانه برقی قهوه‌ساز",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "آریانا هوم",
    "model": "KI-1700",
    "price": 3970000,
    "power": 664,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 102,
    "name": "دلتا خانه لوازم آشپزخانه برقی توستر نان",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "دلتا خانه",
    "model": "KI-1707",
    "price": 1070000,
    "power": 1709,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.9
  },
  {
    "id": 103,
    "name": "سپهر الکتریک لوازم آشپزخانه برقی چای‌ساز",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "سپهر الکتریک",
    "model": "KI-1714",
    "price": 8560000,
    "power": 1345,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.7
  },
  {
    "id": 104,
    "name": "بامو تک لوازم آشپزخانه برقی آبمیوه‌گیری",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "بامو تک",
    "model": "KI-1721",
    "price": 3710000,
    "power": 859,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4
  },
  {
    "id": 105,
    "name": "پارس‌تک لوازم آشپزخانه برقی همزن آشپزخانه",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "پارس‌تک",
    "model": "KI-1728",
    "price": 8350000,
    "power": 812,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.9
  },
  {
    "id": 106,
    "name": "کیان‌الکتریک لوازم آشپزخانه برقی قهوه‌ساز",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "کیان‌الکتریک",
    "model": "KI-1735",
    "price": 1970000,
    "power": 1104,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 107,
    "name": "نوین‌هوم لوازم آشپزخانه برقی توستر نان",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "نوین‌هوم",
    "model": "KI-1742",
    "price": 8990000,
    "power": 1264,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.9
  },
  {
    "id": 108,
    "name": "زرین لوازم لوازم آشپزخانه برقی چای‌ساز",
    "category": "kitchenette",
    "categoryLabel": "لوازم آشپزخانه برقی",
    "icon": "kitchen",
    "brand": "زرین لوازم",
    "model": "KI-1749",
    "price": 4070000,
    "power": 797,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 109,
    "name": "آریانا هوم تلویزیون و صوتی‌تصویری ۴۳ اینچ هوشمند",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "آریانا هوم",
    "model": "TV-1756",
    "price": 20160000,
    "power": 179,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 110,
    "name": "دلتا خانه تلویزیون و صوتی‌تصویری ۵۵ اینچ 4K",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "دلتا خانه",
    "model": "TV-1763",
    "price": 52220000,
    "power": 75,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 3.9
  },
  {
    "id": 111,
    "name": "سپهر الکتریک تلویزیون و صوتی‌تصویری ۶۵ اینچ هوشمند",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "سپهر الکتریک",
    "model": "TV-1770",
    "price": 41050000,
    "power": 79,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.8
  },
  {
    "id": 112,
    "name": "بامو تک تلویزیون و صوتی‌تصویری ساندبار",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "بامو تک",
    "model": "TV-1777",
    "price": 26170000,
    "power": 204,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 3.6
  },
  {
    "id": 113,
    "name": "پارس‌تک تلویزیون و صوتی‌تصویری پروژکتور خانگی",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "پارس‌تک",
    "model": "TV-1784",
    "price": 24720000,
    "power": 94,
    "material": null,
    "warranty": 24,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 114,
    "name": "کیان‌الکتریک تلویزیون و صوتی‌تصویری ۴۳ اینچ هوشمند",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "کیان‌الکتریک",
    "model": "TV-1791",
    "price": 33670000,
    "power": 206,
    "material": null,
    "warranty": 18,
    "inStock": false,
    "rating": 4
  },
  {
    "id": 115,
    "name": "نوین‌هوم تلویزیون و صوتی‌تصویری ۵۵ اینچ 4K",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "نوین‌هوم",
    "model": "TV-1798",
    "price": 38580000,
    "power": 256,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 116,
    "name": "زرین لوازم تلویزیون و صوتی‌تصویری ۶۵ اینچ هوشمند",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "زرین لوازم",
    "model": "TV-1805",
    "price": 24260000,
    "power": 130,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.9
  },
  {
    "id": 117,
    "name": "آریانا هوم تلویزیون و صوتی‌تصویری ساندبار",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "آریانا هوم",
    "model": "TV-1812",
    "price": 25000000,
    "power": 66,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 3.7
  },
  {
    "id": 118,
    "name": "دلتا خانه تلویزیون و صوتی‌تصویری پروژکتور خانگی",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "دلتا خانه",
    "model": "TV-1819",
    "price": 10020000,
    "power": 224,
    "material": null,
    "warranty": 12,
    "inStock": true,
    "rating": 4.5
  },
  {
    "id": 119,
    "name": "سپهر الکتریک تلویزیون و صوتی‌تصویری ۴۳ اینچ هوشمند",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "سپهر الکتریک",
    "model": "TV-1826",
    "price": 40580000,
    "power": 135,
    "material": null,
    "warranty": 18,
    "inStock": true,
    "rating": 4.2
  },
  {
    "id": 120,
    "name": "بامو تک تلویزیون و صوتی‌تصویری ۵۵ اینچ 4K",
    "category": "tv",
    "categoryLabel": "تلویزیون و صوتی‌تصویری",
    "icon": "tv",
    "brand": "بامو تک",
    "model": "TV-1833",
    "price": 27480000,
    "power": 169,
    "material": null,
    "warranty": 36,
    "inStock": true,
    "rating": 4.1
  },
  {
    "id": 121,
    "name": "پارس‌تک ظروف و قابلمه تابه گرانیتی",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "پارس‌تک",
    "model": "CO-1840",
    "price": 1610000,
    "power": null,
    "material": "گرانیتی",
    "warranty": 18,
    "inStock": true,
    "rating": 4.4
  },
  {
    "id": 122,
    "name": "کیان‌الکتریک ظروف و قابلمه قابلمه استیل",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "کیان‌الکتریک",
    "model": "CO-1847",
    "price": 5360000,
    "power": null,
    "material": "استیل ضدزنگ",
    "warranty": 36,
    "inStock": false,
    "rating": 3.9
  },
  {
    "id": 123,
    "name": "نوین‌هوم ظروف و قابلمه سرویس قابلمه ۱۲ پارچه",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "نوین‌هوم",
    "model": "CO-1854",
    "price": 7050000,
    "power": null,
    "material": "چدن",
    "warranty": 18,
    "inStock": false,
    "rating": 3.9
  },
  {
    "id": 124,
    "name": "زرین لوازم ظروف و قابلمه تابه چدن",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "زرین لوازم",
    "model": "CO-1861",
    "price": 2810000,
    "power": null,
    "material": "تفلون مقاوم",
    "warranty": 18,
    "inStock": true,
    "rating": 3.4
  },
  {
    "id": 125,
    "name": "آریانا هوم ظروف و قابلمه سرویس تابه ۶ پارچه",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "آریانا هوم",
    "model": "CO-1868",
    "price": 670000,
    "power": null,
    "material": "مسی",
    "warranty": 12,
    "inStock": false,
    "rating": 4.4
  },
  {
    "id": 126,
    "name": "دلتا خانه ظروف و قابلمه دیگ بخارپز",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "دلتا خانه",
    "model": "CO-1875",
    "price": 5960000,
    "power": null,
    "material": "گرانیتی",
    "warranty": 12,
    "inStock": true,
    "rating": 4
  },
  {
    "id": 127,
    "name": "سپهر الکتریک ظروف و قابلمه تابه گرانیتی",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "سپهر الکتریک",
    "model": "CO-1882",
    "price": 2980000,
    "power": null,
    "material": "استیل ضدزنگ",
    "warranty": 12,
    "inStock": true,
    "rating": 3.8
  },
  {
    "id": 128,
    "name": "بامو تک ظروف و قابلمه قابلمه استیل",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "بامو تک",
    "model": "CO-1889",
    "price": 4140000,
    "power": null,
    "material": "چدن",
    "warranty": 36,
    "inStock": true,
    "rating": 4
  },
  {
    "id": 129,
    "name": "پارس‌تک ظروف و قابلمه سرویس قابلمه ۱۲ پارچه",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "پارس‌تک",
    "model": "CO-1896",
    "price": 1700000,
    "power": null,
    "material": "تفلون مقاوم",
    "warranty": 24,
    "inStock": true,
    "rating": 4.7
  },
  {
    "id": 130,
    "name": "کیان‌الکتریک ظروف و قابلمه تابه چدن",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "کیان‌الکتریک",
    "model": "CO-1903",
    "price": 2700000,
    "power": null,
    "material": "مسی",
    "warranty": 12,
    "inStock": false,
    "rating": 4.3
  },
  {
    "id": 131,
    "name": "نوین‌هوم ظروف و قابلمه سرویس تابه ۶ پارچه",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "نوین‌هوم",
    "model": "CO-1910",
    "price": 4980000,
    "power": null,
    "material": "گرانیتی",
    "warranty": 18,
    "inStock": true,
    "rating": 3.4
  },
  {
    "id": 132,
    "name": "زرین لوازم ظروف و قابلمه دیگ بخارپز",
    "category": "cookware",
    "categoryLabel": "ظروف و قابلمه",
    "icon": "cookware",
    "brand": "زرین لوازم",
    "model": "CO-1917",
    "price": 1300000,
    "power": null,
    "material": "استیل ضدزنگ",
    "warranty": 24,
    "inStock": true,
    "rating": 4.4
  }
];
const CATEGORIES = [
  {
    "key": "fridge",
    "label": "یخچال و فریزر",
    "icon": "fridge"
  },
  {
    "key": "washer",
    "label": "ماشین لباسشویی",
    "icon": "washer"
  },
  {
    "key": "dishwasher",
    "label": "ماشین ظرفشویی",
    "icon": "dishwasher"
  },
  {
    "key": "stove",
    "label": "اجاق گاز و هود",
    "icon": "stove"
  },
  {
    "key": "microwave",
    "label": "مایکروویو",
    "icon": "microwave"
  },
  {
    "key": "vacuum",
    "label": "جاروبرقی",
    "icon": "vacuum"
  },
  {
    "key": "fan",
    "label": "کولر و پنکه",
    "icon": "fan"
  },
  {
    "key": "iron",
    "label": "اتو و بخارشو",
    "icon": "iron"
  },
  {
    "key": "kitchenette",
    "label": "لوازم آشپزخانه برقی",
    "icon": "kitchen"
  },
  {
    "key": "tv",
    "label": "تلویزیون و صوتی‌تصویری",
    "icon": "tv"
  },
  {
    "key": "cookware",
    "label": "ظروف و قابلمه",
    "icon": "cookware"
  }
];
